version: "3.9"

services:
  contreasy-db:
    image: postgres
    container_name: contreasy-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
